name: Docker

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
          docker build -t sdrobov/goodmorningbot:aarch64 --platform=linux/aarch64 .
          docker build -t sdrobov/goodmorningbot:amd64 --platform=linux/amd64 .

      - name: Push
        run: |
          docker push sdrobov/goodmorningbot:aarch64
          docker push sdrobov/goodmorningbot:amd64

      - name: Create manifest
        run: |
          docker manifest create sdrobov/goodmorningbot:latest sdrobov/goodmorningbot:amd64 sdrobov/goodmorningbot:aarch64
          docker manifest push sdrobov/goodmorningbot:latest
